### ISSUE TITLE
Multi-World Server Issues

### ISSUE THREAD

**Issue by BernardoXD72** [jpenilla/squaremap#156]
hi, i have multiple worlds on my server due to a mod (ad astra) but i want squaremap to just show the normal world , but its showing another world. how do i change that?

**Comment by BernardoXD72** [comment]
my version of the mod is Fabric 1.19.2 1.1.8

**Comment by jpenilla** [comment]
https://github.com/jpenilla/squaremap/wiki/Common-Questions#how-do-i-disableenable-worlds

**Comment by BernardoXD72** [comment]
i am having problems trying to put the disable worlds code in the link to the config.yml file, could you help me if you have time?

**Comment by jpenilla** [comment]
Do you only want the overworld? Or also nether and end?

**Comment by BernardoXD72** [comment]
only overworld

**Comment by jpenilla** [comment]
Here is the default `world-settings` section, modified to only enable the map for the overworld.
```yaml
world-settings:
    minecraft:overworld:
        map:
            enabled: true
    default:
        map:
            enabled: false
            display-name: '{world}'
            order: 0
            icon: ''
            max-render-threads: -1
            iterate-up: false
            max-height: -1
            biomes:
                enabled: true
                blend-biomes: 3
            glass:
                clear: true
            lava:
                checkerboard: true
            water:
                clear-depth: true
                checkerboard: false
            zoom:
                maximum: 3
                default: 3
                extra: 2
            background-render:
                enabled: true
                max-chunks-per-interval: 1024
                interval-seconds: 15
                max-render-threads: -1
            markers:
                update-interval-seconds: 5
                spawn-icon:
                    enabled: true
                    show-controls: true
                    default-hidden: false
                    layer-priority: 0
                    z-index: 0
                world-border:
                    enabled: true
                    show-controls: true
                    default-hidden: false
                    layer-priority: 1
                    z-index: 1
            visibility-limits:
            -   type: world-border
                enabled: 'false'
        player-tracker:
            enabled: true
            update-interval-seconds: 1
            show-controls: true
            default-hidden: false
            layer-priority: 2
            z-index: 2
            nameplate:
                enabled: true
                show-head: true
                heads-url: https://mc-heads.net/avatar/{uuid}/16
                show-armor: true
                show-health: true
            hide:
                invisible: true
                spectators: true
            use-display-names: false
```
