### ISSUE TITLE
Rendering the Nether Roof 

### ISSUE THREAD

**Issue by Dyljyn** [jpenilla/squaremap#269]
I'm in the process of setting up the map so it shows our Nether Hub, which has been built on top of the Nether Roof. I want to only show the blocks above the Nether Roof, including the bedrock of the Nether Roof.

How to potentially get the nether roof to render was described in [this comment on another issue](https://github.com/jpenilla/squaremap/issues/40#issuecomment-1831180446). Unfortunately, this does not seem to work.

I am currently a bit lost on how this could actually be achieved.

**Comment by Dyljyn** [comment]
I've done some testing: It seems that the map is always looking for a roof in the nether.

At build height I created a little square as a roof with 3 layers:
- Y=255: Full square several colors
- Y=254: Inner outline
- Y=253: Outer outline

<table>
<tr><td align="center">Top view</td><td align="center">Bottom view</td></tr>
<tr>
<td>

![2024-08-26_15 46 07](https://github.com/user-attachments/assets/fcc12c61-c2b3-44bf-9ba0-28a0f9fba964)

</td>
<td>

![2024-08-26_15 46 14](https://github.com/user-attachments/assets/cfd6bb87-ac79-4db6-b844-a39f98705f79)

</td>
</tr>
</table>

In the result you'll see:
1. Only the outer outline is shown, because of the 1 block air gap
2. The nether roof (bedrock block) is shown for all the other blocks within the square, again thanks to the air blocks in between this roof and "The Nether Roof" at Y=128

![image](https://github.com/user-attachments/assets/959cad52-ce5f-40c8-a28d-939c52766569)

<details>
<summary>Config</summary>

```yaml
config-version: 2
settings:
    language-file: lang-en.yml
    debug-mode: false
    update-checker: true
    web-address: localhost:8080
    web-directory:
        path: web
        auto-update: true
    image-quality:
        compress-images:
            enabled: false
            value: 0.0
    internal-webserver:
        enabled: true
        bind: 0.0.0.0
        port: 8080
    ui:
        coordinates:
            enabled: true
        link:
            enabled: true
        sidebar:
            pinned: pinned
    commands:
        main-command-label: squaremap
        main-command-aliases:
        - map
    render-progress-logging:
        enabled: true
        interval-seconds: 1
world-settings:
    default:
        map:
            enabled: true
            display-name: '{world}'
            order: 0
            icon: ''
            max-render-threads: -1
            iterate-up: false
            biomes:
                enabled: true
                blend-biomes: 3
            glass:
                clear: true
            lava:
                checkerboard: true
            water:
                clear-depth: true
                checkerboard: false
            zoom:
                maximum: 3
                default: 3
                extra: 5
            background-render:
                enabled: true
                max-chunks-per-interval: 1024
                interval-seconds: 15
                max-render-threads: -1
            max-height: -1
            markers:
                update-interval-seconds: 5
                spawn-icon:
                    enabled: true
                    show-controls: true
                    default-hidden: false
                    layer-priority: 0
                    z-index: 0
                world-border:
                    enabled: true
                    show-controls: true
                    default-hidden: false
                    layer-priority: 1
                    z-index: 1
            visibility-limits:
            -   type: world-border
                enabled: 'false'
        player-tracker:
            enabled: true
            update-interval-seconds: 1
            show-controls: true
            default-hidden: false
            layer-priority: 2
            z-index: 2
            nameplate:
                enabled: true
                show-head: true
                heads-url: https://mc-heads.net/avatar/{uuid}/16
                show-armor: true
                show-health: true
            hide:
                invisible: true
                spectators: true
            use-display-names: false
    minecraft:the_nether:
        map:
            enabled: true
            display-name: Nether
            iterate-up: false
            max-height: 256
            glass:
                clear: false

```

</details>

---

My guess is that it has something to do with the "exception" to dimensions with a ceiling stated in the following code:

https://github.com/jpenilla/squaremap/blob/2af338922c40fd4dfabbc13dcad1b7cbeb3059d8/common/src/main/java/xyz/jpenilla/squaremap/common/task/render/AbstractRender.java#L429C9-L434C10

_I'm not familiar with Java or Minecraft modding so this is currently as far as my programming knowledge goes for this matter._
