### ISSUE TITLE
Can no longer set aliases for quaremap commands

### ISSUE THREAD

**Issue by lerokko** [jpenilla/squaremap#271]
We recent updated our server to squaremap version 1.2.6. Since then I am no longer able to set aliases for it.
The command /show and /hide do not work but typing them out with squaremap does work. Could this be related to the new `main-command-aliases` feature?

config.yml excerpt:
``` yml
    commands:
        main-command-label: squaremap
        main-command-aliases: []
```

Aliases:
``` yml
  show:
  - squaremap show
  hide:
  - squaremap hide
```

Log excerpt:
	Line 126: [12:36:24] [Server thread/INFO]: [squaremap] Loading server plugin squaremap v1.2.6
	Line 126: [12:36:24] [Server thread/INFO]: [squaremap] Loading server plugin squaremap v1.2.6
	Line 161: [12:36:37] [Server thread/INFO]: [squaremap] Enabling squaremap v1.2.6
	Line 161: [12:36:37] [Server thread/INFO]: [squaremap] Enabling squaremap v1.2.6
	Line 177: [12:36:45] [Server thread/INFO]: [squaremap] Internal webserver running on 0.0.0.0:8080
	Line 579: [12:38:20] [Server thread/WARN]: Could not register alias show because it contains commands that do not exist: squaremap show
	Line 580: [12:38:20] [Server thread/WARN]: Could not register alias hide because it contains commands that do not exist: squaremap hide
