### ISSUE TITLE
how to add an ssl certificate

### ISSUE THREAD

**Issue by VaskaGROM** [jpenilla/squaremap#358]
how to add an ssl certificate for connection https://

**Comment by pianoman911** [comment]
Bind the web server locally, set web-address and use a reverse proxy setup, easiest way to go

**Comment by cfazilleau** [comment]
I did this using a reverse proxy using netlify, it is free and very simple. here is an exemple of the config file I used:

[netlify.toml](https://docs.netlify.com/configure-builds/file-based-configuration/)
```toml
[[redirects]]
from = "/*"
to = "http://<your-ip>:<your-port>/:splat"
status = 200
force = true
```
