### ISSUE TITLE
Cannot rename a world named "2022"

### ISSUE THREAD

**Issue by hamcoremusic** [jpenilla/squaremap#37]
Hello!

I am having a weird issue where I am unable to rename/apply settings to the overworld map I have titled "2022". See my config below!

```yaml
    2022:
        map:
            enabled: true
            display-name: 'Overworld'
```

The world folder name is 2022 and it displays as "minecraft:overworld" right now on the sidebar
