### ISSUE TITLE
Ability to define multiple maps for the same dimension

### ISSUE THREAD

**Issue by n-aspen** [jpenilla/squaremap#40]
It'd be really nice to make multiple maps for the same dimension using different settings like `visibility-limits` and `max-height`. 

An example use case would be to have two maps of the Nether, one for the lower Nether and one for the Nether roof. That's currently not possible and you have to choose which one you want to display.

**Comment by TheDogg** [comment]
@n-aspen I'm curious as how your config file looks to generate a map of the nether roof?  I can't seem to figure out how to do it

**Comment by n-aspen** [comment]
@TheDogg You can't do both the nether roof and the nether itself at the moment, so I just have the nether itself. But iirc, you can remove the `max-height` entry in the nether map section and make sure that you **don't** have the `iterate-up` entry set to `true`. This will just map the topmost blocks of the nether, in effect the nether roof, just like it does for the overworld.

**Comment by n-aspen** [comment]
I'm still really interested in this feature. I'd try to contribute to the code myself, but the front end is well beyond me atm. 

I feel like it'd be easiest to change the existing `world-settings` section to use an unrelated unique name for each map and then define the world name within the entry for that map. For example

```yaml
    Overworld:
        dimension: minecraft:overworld
        map:
            display-name: Overworld
    The_Nether
        dimension: minecraft:the_nether
        map:
            display-name: The Nether
            max-height: 83
            glass:
                clear: false
    The_Nether_Roof
        dimension: minecraft:the_nether
        map:
            display-name: The Nether Roof
            glass:
                clear: false
    The_End:
        dimension: minecraft:the_end
        map:
            display-name: The End
```
In the above example the keys are used to distinguish the maps from each other and are then linked to the `dimension` they render and "mark". 
When the API is asked for a MapWorld it can return the maps for that dimension, using the same input already provided. Then when markers are rendered on a given LayerProvider, they won't be rendered if they're outside of the defined render limits of the associated map.
