### ISSUE TITLE
Prevent rendering outside of worldborder

### ISSUE THREAD

**Issue by fizzrepo** [jpenilla/squaremap#45]
Is there any way to prevent rendering outside of worldborder or limiting visibility outside of the worldborder?
I have a flat 250x250 world and I don't want to render the grass outside of the worldborder.

**Comment by jpenilla** [comment]
See `visibility-limits` in the config https://github.com/jpenilla/squaremap/wiki/Default-config.yml

You will want to set the world border limit to true.

**Comment by fizzrepo** [comment]
![image](https://user-images.githubusercontent.com/58730469/163361130-0fdab582-3018-43ae-a959-a553415cb1f6.png)
This doesn't seem to be working, here's my config.

```yaml
config-version: 2
settings:
    language-file: lang-en.yml
    debug-mode: false
    update-checker: true
    web-address: http://localhost:25569
    web-directory:
        path: web
        auto-update: true
    image-quality:
        compress-images:
            enabled: false
            value: 0.0
    internal-webserver:
        enabled: true
        bind: 0.0.0.0
        port: 25569
    ui:
        coordinates:
            enabled: true
        link:
            enabled: true
        sidebar:
            pinned: unpinned
    commands:
        main-command-label: squaremap
        main-command-aliases:
        - map
    render-progress-logging:
        enabled: true
        interval-seconds: 1
world-settings:
    minecraft:overworld:
        map:
            enabled: false
    default:
        map:
            enabled: true
            display-name: '{world}'
            order: 0
            icon: ''
            max-render-threads: -1
            iterate-up: false
            max-height: -1
            biomes:
                enabled: true
                blend-biomes: 3
            glass:
                clear: true
            lava:
                checkerboard: true
            water:
                clear-depth: true
                checkerboard: false
            zoom:
                maximum: 3
                default: 3
                extra: 2
            background-render:
                enabled: true
                max-chunks-per-interval: 1024
                interval-seconds: 15
                max-render-threads: -1
            markers:
                update-interval-seconds: 5
                spawn-icon:
                    enabled: true
                    show-controls: true
                    default-hidden: false
                    layer-priority: 0
                    z-index: 0
                world-border:
                    enabled: true
                    show-controls: true
                    default-hidden: false
                    layer-priority: 1
                    z-index: 1
            visibility-limits:
            -   type: world-border
                enabled: 'true'
        player-tracker:
            enabled: false
            update-interval-seconds: 1
            show-controls: false
            default-hidden: false
            layer-priority: 2
            z-index: 2
            nameplate:
                enabled: true
                show-head: true
                heads-url: https://mc-heads.net/avatar/{uuid}/16
                show-armor: true
                show-health: true
            hide:
                invisible: true
                spectators: true
            use-display-names: false
```
