### ISSUE TITLE
order is not working

### ISSUE THREAD

**Issue by hkkongou** [jpenilla/squaremap#46]
no matter i have 
```
world-settings:
    default:
        map:
            enabled: true
            display-name: '{world}'
            order: 0
    minecraft:the_nether:
        map:
            enabled: true
            display-name: '{world}'
            order: 1
```
or 
```
world-settings:
    default:
        map:
            enabled: true
            display-name: '{world}'
            order: 1
    minecraft:the_nether:
        map:
            enabled: true
            display-name: '{world}'
            order: 0
```

overworld is still displaying as the default map when map is loaded in any browser
