### ISSUE TITLE
Fully disable player list when player-tracker is disabled

### ISSUE THREAD

**Issue by Titaniumtown** [jpenilla/squaremap#59]
I have disabled everything relating to showing players on the map, but the `Players (0/20)` still persists even though it has no functionality due to my configuration options. Could this be changed so this doesn't exist when the respective option is disabled?

Image of problem:
![image](https://user-images.githubusercontent.com/11786225/174467724-8ff24408-aaaa-47ce-9ca5-f6cbef6f55d8.png)

I just installed this mod, so lmk if I simply got the config wrong (I tried disabling everything to see if the desired effect would take place):
```yaml
        player-tracker:
            enabled: false
            update-interval-seconds: 99999999
            show-controls: false
            default-hidden: false
            layer-priority: 2
            z-index: 2
            nameplate:
                enabled: false
                show-head: false
                heads-url: https://mc-heads.net/avatar/{uuid}/16
                show-armor: false
                show-health: false
            hide:
                invisible: true
                spectators: true
            use-display-names: false
```
