### ISSUE TITLE
Startup errors

### ISSUE THREAD

**Issue by agoniaprivat** [jpenilla/squaremap#64]
https://mclo.gs/NfFpOFD

Latest build.

**Comment by jpenilla** [comment]
You have an ancient config with invalid values

from Discord pins:

Getting an error message containing `No such entry 'minecraft:dark_forest_hills' in registry 'ResourceKey[minecraft:root / minecraft:worldgen/biome]'` or similar on startup after updating squaremap?

This is due to the old default config containing biomes which were removed in 1.18, and a recent squaremap update now validating biomes in configs.

To fix this, replace the values for `world-settings.default.color-overrides.biomes.foliage` in `advanced.yml` with the new defaults: 

```yml
world-settings:
  default:
    # other settings...
    color-overrides:
      biomes:
        foliage:
          minecraft:bamboo_jungle: '#1f8907'
          minecraft:sparse_jungle: '#1f8907'
          minecraft:dark_forest: '#1c7b07'
          minecraft:jungle: '#1f8907'
```
